config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :genders

  devise_for :users

  root 'home#index'

end

app/models/gender.rb
class Gender < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  before_action :set_gender, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @genders = Gender.all
    respond_with(@genders)
  end

  def show
    respond_with(@gender)
  end

  def new
    @gender = Gender.new
    respond_with(@gender)
  end

  def edit
  end

  def create
    @gender = Gender.new(gender_params)
    @gender.save
    respond_with(@gender)
  end

  def update
    @gender.update(gender_params)
    respond_with(@gender)
  end

  def destroy
    @gender.destroy
    respond_with(@gender)
  end

  private
    def set_gender
      @gender = Gender.find(params[:id])
    end

    def gender_params
      params.require(:gender).permit(:name, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/genders/_form.html.erb
<%= form_for(@gender) do |f| %>
  <% if @gender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gender.errors.count, "error") %> prohibited this gender from being saved:</h2>

      <ul>
      <% @gender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genders/edit.html.erb
<h1>Editing Gender</h1>

<%= render 'form' %>

<%= link_to 'Show', @gender %> |
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genders.each do |gender| %>
      <tr>
        <td><%= gender.name %></td>
        <td><%= gender.user %></td>
        <td><%= link_to 'Show', gender %></td>
        <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
        <td><%= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gender', new_gender_path %>

app/views/genders/new.html.erb
<h1>New Gender</h1>

<%= render 'form' %>

<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gender.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @gender.user %>
</p>

<%= link_to 'Edit', edit_gender_path(@gender) %> |
<%= link_to 'Back', genders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PPEstate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>